### ISSUE TITLE
Occupied too much memory when showing the large file.

### ISSUE THREAD

**Issue by messyidea** [hacdias/filemanager#100]
### 1. Have you downloaded File Manager from caddyserver.com? If yes, when have you done that? If no, and you are running a custom build, which is the revision of File Manager's repository?

Yes. The newest caddy with filemanager plugin. Version 0.10.4.

### 2. What is your entire Caddyfile?
```text
:2015 {
    filemanager
}
```

### 3. What are you trying to do?
It will occupied too much memory when showing the large file.

### 4. What did you expect to see?
Usually, Caddy with filemanager plugin will occupy about 20mb memory.
But, when I open the page like this,
![Imgur](http://i.imgur.com/Qt0Xflk.png)
Caddy will occupy about 100+ mb memory (a bit larger than the size of the big file).
It's unfriendly to some low memory server.

**Comment by hacdias** [comment]
Oh, I think I just replicated this: it also happens when you download a file?

**Comment by messyidea** [comment]
Thank you~
