### ISSUE TITLE
Cannot download caddy with this plugin on https://caddyserver.com/download

### ISSUE THREAD

**Issue by crvv** [hacdias/filemanager#98]
### 1. Have you downloaded File Manager from caddyserver.com? If yes, when have you done that? If no, and you are running a custom build, which is the revision of File Manager's repository?

Yes. 
Thu Jun 29 11:02:18 UTC 2017

### 3. What are you trying to do?
Download Caddy with plugin filemanager on caddyserver.com.

### 4. What did you expect to see?
Download successfully.

### 5. What did you see instead (give full error messages and/or log)?
> Oops. Maybe one of the plugins is temporarily broken. Try adjusting which plugins you've selected, or download Caddy from GitHub without any plugins (it will always work!).

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?
`curl https://caddyserver.com/download/darwin/amd64?plugins=http.filemanager`

It seems that the hugo plugin is also broken.

**Comment by hacdias** [comment]
Hello @crvv! Thanks for reporting. I'm aware of this and I'm waiting for @mholt to wake up 😅 Different timezones...  I've already tried to solve it, but I'm getting an error too when trying to change the options on our console.

Anyway, sorry for this. It was my fault. I'm making a complete rewrite on how this plugin works, and yesterday I went to the Developers Panel and changed some options. I shouldn't have done it. But I hope this gets fixed today!

**Comment by mholt** [comment]
Might also be a bug in the devportal (my fault) -- just not sure yet!

**Comment by hacdias** [comment]
Solved! Thanks @mholt 😄

**Comment by hacdias** [comment]
Ping @crvv
